apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "YOUR_DOCKER_USERNAME",
          "password": "YOUR_DOCKER_PASSWORD_OR_TOKEN",
          "auth": "BASE64_ENCODED_USERNAME_PASSWORD"
        }
      }
    }
